event/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.main),
    path('event/<int:ID>/', views.event),
    path('rules/', views.rules),
    path('special/', views.special),
    path('leaderboard/', views.leader),
    path('winners/', views.winners),
    path('signup/', views.signup),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate, name='activate'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='password.html'), name='password_reset_confirm'),
    path('reset/done/', views.reset_done, name='password_reset_complete'),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('login/', LoginView.as_view(template_name='signin.html'), name = 'login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

knock_knock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

event/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.urls import reverse



# Create your models here.
class CustomUser(AbstractUser):
    score = models.IntegerField(default=0, blank= True)
    contact = models.CharField(max_length=10, blank= True)
    time_submission = models.DateTimeField(default=now)
    strin = "0"
    number=12
    for i in range(1,number):
        strin = strin+"0"
    answered = models.TextField(max_length=200, default=strin)

    def publish(self):
        self.save()

    def get_absolute_url(self):
        return reverse()

class Questions(models.Model):
    number = models.IntegerField(default=0)
    query = models.CharField(max_length=800)
    option1 = models.CharField(max_length=30)
    option2 = models.CharField(max_length=30)
    option3 = models.CharField(max_length=30)
    option4 = models.CharField(max_length=30)
    CHOICE = (
        (1, 'A'),
        (2, 'B'),
        (3, 'C'),
        (4, 'D'),
    )
    answer = models.IntegerField(default=0, choices=CHOICE)

class Event(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()

class Special(models.Model):
    query = models.TextField(max_length=1200, default=" ")
    answer = models.CharField(max_length=50, default=" ")

event/forms.py
from django import forms
from .models import CustomUser, Questions, Special


class CustomUserSignupForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'contact', 'password')



class EventAnswerForm(forms.Form):
    CHOICES = [(1, 'A'),
               (2, 'B'),
               (3, 'C'),
               (4, 'D'), ]
    user_answer = forms.ChoiceField(choices=CHOICES)

    def validate(self,ID):
        actual = Questions.objects.get(number=ID).answer
        user = self.cleaned_data['user_answer']
        if int(actual) == int(user):
            return 1
        else:
            return 0

class SpecialAnswerForm(forms.Form):

    user_answer = forms.CharField(max_length=200)

    def validate(self):
        actual = Special.objects.all()
        actual_answer = actual[0].answer
        print(actual_answer)
        user = self.cleaned_data['user_answer']
        print(user)
        if actual_answer is user:
            return 1
        else:
            return 0

templates/leaderboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Leaderboard | Maths N Tech Club</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'images/icons/trophy.png' %}"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/rules.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="../"><span class="glyphicon glyphicon-search"></span> Knock Knock</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">

      <li></li>
    </ul>
 <!--   <ul class="nav navbar-nav navbar-right">
      <li><a href="../"><span class="glyphicon glyphicon-home"></span> Home</a></li>
      <li><a href="../login/"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
    </ul>-->
  </div>
</div>
</nav>
<div class="container">

  <h3> <i class="fa fa-trophy" style="color:#FFD700;"></i> Leaderboard</h3>
  <br>
  <p> Well done guys! <i class="fa fa-glass" style="color:#1E90FF;"></i></p>
</div>
<div class="container">
<br>                                                                                      
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Points</th>
      </tr>
    </thead>
    {% for each in everyone %}
      <tbody>
      <tr>
        <td>{{each.first_name}} {{each.last_name}}</td>
        <td>{{each.username}}</td>
        <td>{{each.score}}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  </div>
</div>

templates/notstarted.html
<html>
    <head></head>
    <body>
        <p>Contest has not started yet, you will be redirected to rules page</p>
        <script type="text/javascript">
        function Redirect()
    {
        location.replace("http://206.189.142.107:8000/rules/")
    }
    document.write("You will be redirected to a new page in 5 seconds");
    setTimeout('Redirect()', 5000);
    </script>
    </body>
</html>

templates/password_reset_confirm.html
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    {% else %}<p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

templates/password_reset_done.html
<p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>

templates/questions.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns:color="http://www.w3.org/1999/xhtml">
<head>
  <title>Questions | Maths N Tech Club</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'images/icons/questions.png' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/questions.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="../../event/1/"><span class="glyphicon glyphicon-search"></span> Knock Knock</a>
    </div>
     <div class="collapse navbar-collapse" id="myNavbar">


    <ul class="nav navbar-nav navbar-right">
      <li class="fa fa-trophy"><a href="../../leaderboard/">Leaderboard</a></li>
   <!--   <li><a href="../../logout/"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li> -->
    </ul>
  </div>
</div>
</nav>
<div class="container-fluid">
  <h2>Round 1</h2>
  <div id="page">
    <p class="alignright">Time Remaining: <span id="demo"></span></p>
  </div>
  <div style="clear: both;"></div>​
</div>
<div class="container-fluid">
  <div class="card">
<nav class="navbar1 navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <p class="navbar-brand">Question Number</p>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar1">
    <ul class="nav navbar-nav">
      {% if query1 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../1/">Question 1</a></li>
      {% else %}
      <li><a href="../1/">Question 1</a></li>
      {% endif %}
      {% if query2 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../2/">Question 2</a></li>
      {% else %}
      <li><a href="../2/">Question 2</a></li>
      {% endif %}
      {% if query3 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../3/">Question 3</a></li>
      {% else %}
      <li><a href="../3/">Question 3</a></li>
      {% endif %}
      {% if query4 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../4/">Question 4</a></li>
      {% else %}
      <li><a href="../4/">Question 4</a></li>
      {% endif %}
      {% if query5 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../5/">Question 5</a></li>
      {% else %}
      <li><a href="../5/">Question 5</a></li>
      {% endif %}
      {% if query6 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../6/">Question 6</a></li>
      {% else %}
      <li><a href="../6/">Question 6</a></li>
      {% endif %}
      {% if query7 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../7/">Question 7</a></li>
      {% else %}
      <li><a href="../7/">Question 7</a></li>
      {% endif %}
      {% if query8 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../8/">Question 8</a></li>
      {% else %}
      <li><a href="../8/">Question 8</a></li>
      {% endif %}
      {% if query9 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../9/">Question 9</a></li>
      {% else %}
      <li><a href="../9/">Question 9</a></li>
      {% endif %}
      {% if query10 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../10/">Question 10</a></li>
      {% else %}
      <li><a href="../10/">Question 10</a></li>
      {% endif %}
      {% if query11 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../../special/">Question 11</a></li>
      {% else %}
      <li><a href="../../special/">Question 11</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
</div>
</div>
<form method="POST">
  {% csrf_token %}
  <div class="container-fluid">
<div class="card">
  <div class="card-header">
    <h5><strong>Question {{ID}}</strong></h5>
  </div>
  <br>
  <br>
  <div class="card-body">
    <h5 class="card-title">{{queries.query}}</h5>
    <p class="card-text">
<ul class="answers">
<input type="radio" name="user_answer" value="1" id="id_user_answer">{{queries.option1}}<br/>
<input type="radio" name="user_answer" value="2" id="id_user_answer">{{queries.option2}}<br/>
<input type="radio" name="user_answer" value="3" id="id_user_answer">{{queries.option3}}<br/>
<input type="radio" name="user_answer" value="4" id="id_user_answer">{{queries.option4}}<br/>
</ul></p>
  </div>
</div>
<br>
  <div class="container-fluid text-center" >
    <button class="btn btn-lg" type="submit">Submit</button>
  </div>
</br>
</form>
<script>
// Set the date we're counting down to
//Time when the contest ends
var countDownDate = new Date("Sept 29, 2018 12:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();
    
    // Find the distance between now and the count down date
    var distance = countDownDate - now;
    
    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";
    
    // If the count down is over, write some text 
    if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "Contest Ended";
        redirect();
    }
    function redirect(){
    document.write("This page will be reirected in 3 seconds");
        setTimeout(function(){  location.replace("http://206.189.142.107:8000/leaderboard/")}, 3000);
}
}, 1000);
</script>
</body>
</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Sign Up | Maths N Tech Club</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/user.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main1.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST" novalidate>
					{% csrf_token %}

					<span class="login100-form-title p-b-43">
						Sign Up
					</span>
					<div class="wrap-input100">
						<input class="input100" type="text" name="first_name" maxlength="30" id="id_first_name">
						<span class="focus-input100"></span>
						<span class="label-input100">First Name</span>
					</div>
					<div class="wrap-input100">
						<input class="input100" type="text" name="last_name" maxlength="150" id="id_last_name">
						<span class="focus-input100"></span>
						<span class="label-input100">Last Name</span>
					</div>
					<div class="wrap-input100">
						<input class="input100" type="text" name="username" required="" maxlength="150" id="id_username">
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>
					<div class="wrap-input100">
						<input class="input100" type="text" name="contact" maxlength="10" id="id_contact">
						<span class="focus-input100"></span>
						<span class="label-input100">Contact Number</span>
					</div>

					<div class="wrap-input100">
						<input class="input100" type="email" name="email" maxlength="254" id="id_email">
						<span class="focus-input100"></span>
						<span class="label-input100">Email</span>
					</div>

					<div class="wrap-input100">
						<input class="input100" name="password" id="id_password" required="">
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign Up
						</button>
					</div>

					<div class="text-center p-t-46 p-b-20">
						<span class="txt2">
					<!--		Already registered? <a href="../login/"><u>Sign In</u></a> -->
						</span>
					</div>

				</form>

				<div class="login100-more" style="background-image: url('/static/images/1.png');">
				</div>
			</div>
		</div>
	</div>
	
	

	
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/special.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns:color="http://www.w3.org/1999/xhtml">
<head>
  <title>Questions | Maths N Tech Club</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{% static 'images/icons/questions.png' %}"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/questions.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../../event/1/"><span class="glyphicon glyphicon-search"></span> Knock Knock</a>
    </div>
     <div class="collapse navbar-collapse" id="myNavbar">


    <ul class="nav navbar-nav navbar-right">
  <!--    <li><a href="../../logout/"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li> -->
    </ul>
  </div>
</div>
</nav>
<div class="container-fluid">
  <h2>Round 1</h2>
  <div id="page">
    <p class="alignright">Time Remaining: <span id="demo"></span></p>
  </div>
  <div style="clear: both;"></div>​
</div>
<div class="container-fluid">
  <div class="card">
<nav class="navbar1 navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand">Question Number</p>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar1">
    <ul class="nav navbar-nav">
      {% if query1 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/1/">Question 1</a></li>
      {% else %}
      <li><a href="../event/1/">Question 1</a></li>
      {% endif %}
      {% if query2 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/2/">Question 2</a></li>
      {% else %}
      <li><a href="../event/2/">Question 2</a></li>
      {% endif %}
      {% if query3 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/3/">Question 3</a></li>
      {% else %}
      <li><a href="../event/3/">Question 3</a></li>
      {% endif %}
      {% if query4 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/4/">Question 4</a></li>
      {% else %}
      <li><a href="../event/4/">Question 4</a></li>
      {% endif %}
      {% if query5 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/5/">Question 5</a></li>
      {% else %}
      <li><a href="../event/5/">Question 5</a></li>
      {% endif %}
      {% if query6 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/6/">Question 6</a></li>
      {% else %}
      <li><a href="../event/6/">Question 6</a></li>
      {% endif %}
      {% if query7 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/7/">Question 7</a></li>
      {% else %}
      <li><a href="../event/7/">Question 7</a></li>
      {% endif %}
      {% if query8 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/8/">Question 8</a></li>
      {% else %}
      <li><a href="../event/8/">Question 8</a></li>
      {% endif %}
      {% if query9 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/9/">Question 9</a></li>
      {% else %}
      <li><a href="../event/9/">Question 9</a></li>
      {% endif %}
      {% if query10 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../event/10/">Question 10</a></li>
      {% else %}
      <li><a href="../event/10/">Question 10</a></li>
      {% endif %}
      {% if query11 != 0 %}
      <li style="background-color: #8bca8b;"><a href="../../special/">Question 11</a></li>
      {% else %}
      <li><a href="../../special/">Question 11</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
</div>
</div>
<form method="POST">
  {% csrf_token %}
  <div class="container-fluid">
<div class="card">
  <div class="card-header">
    <h5><strong>Question {{ID}}</strong></h5>
  </div>
  <br>
  <br>
  <div class="card-body">
    <h5 class="card-title">{{queries.query}}</h5>
    <p class="card-text">
<ul class="answers">
<p>
    <label for="id_user_answer">Answer:</label>
    <input type="text" name="user_answer" maxlength="200" required="" id="id_user_answer">
  </p>
</ul>
  </div>
</div>
<br>
  <div class="container-fluid text-center" >
    <button class="btn btn-lg" type="submit">Submit</button>
  </div>
</br>
</form>
<script>
// Set the date we're counting down to
//Time when the contest ends
var countDownDate = new Date("Sept 29, 2018 12:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();

    // Find the distance between now and the count down date
    var distance = countDownDate - now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    // Output the result in an element with id="demo"
    document.getElementById("demo").innerHTML = days + "d " + hours + "h "
    + minutes + "m " + seconds + "s ";

    // If the count down is over, write some text
    if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "Contest Ended";
        redirect();
    }

    function redirect(){
    document.write("This page will be reirected in 3 seconds");
        setTimeout(function(){  location.replace("http://127.0.0.1:8000/leaderboard/")}, 3000);
}

}, 1000);
</script>
</body>
</html>

templates/winners.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Winners</title>
</head>
{% if request.user.is_superuser %}
<body>
    {% for student in participants %}
    <pre>
        <p>User Name: {{student.username}}</p>
        <p>First Name: {{student.first_name}}</p>
        <p>Last Name: {{student.last_name}}</p>
        <p>Conatct No: {{student.contact}}</p>
    </pre>
    <p>------------------------------------------------------------</p>
    {% endfor %}
</body>
{% else %}
<body>
    <h>Access restricted</h>
    <script type="text/javascript">
        function Redirect()
    {
        window.location="https://www.knockknock.in.net/";
    }
    document.write("You will be redirected to a new page in 5 seconds");
    setTimeout('Redirect()', 5000);
    </script>
</body>
{% endif %}
</html>